version: '3'
services:
  jupyter:
    image: jupyter/base-notebook
    restart: always
    ports:
      - "8888:8888"
    command: bash -c "git clone --depth 1 https://github.com/mnagaku/2017-lectures.git -b pwd ; jupyter notebook --NotebookApp.token='jxta'"
